"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import golfBall from "../../../public/golf-ball.png";
import { calculateSurplus, getOverlayAmount, getUnlockedTiers } from "@/lib/portal-logic";
import { playPortalSound } from "@/lib/sounds";
import { getTierFromContribution } from "@/lib/tiers";
import { supabase } from "@/lib/supabase/client";

function formatMoney(value: number | string | null | undefined): string {
  const n = Number(value ?? 0);
  if (!Number.isFinite(n)) return "$0";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);
}

function portalFundTestMode(): 0 | 1 | 2 {
  // Change return value to test different states — remove when Supabase supplies fund data
  return 2;
}

const TIER_THRESHOLDS = [0, 100, 500, 2000, 10000];

export default function PortalPage() {
  const router = useRouter();
  const [showWelcome, setShowWelcome] = useState(false);
  const [showTierInfo, setShowTierInfo] = useState(false);
  const [showRules, setShowRules] = useState(false);
  const [showTierUnlock, setShowTierUnlock] = useState(false);
  const [profile, setProfile] = useState<any>(null);
  const [contests, setContests] = useState<any[]>([]);

  const prevTierRef = useRef<number | null>(null);

  useEffect(() => {
    const loadProfile = async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession();

      if (!session?.user?.id) return;

      const { data } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", session.user.id)
        .single();

      if (data) {
        setProfile(data);

        const hasSeen = localStorage.getItem("cc_portal_welcome_seen");

        if (!hasSeen) {
          setShowWelcome(true);
        }
      }
    };

    void loadProfile();
  }, []);

  useEffect(() => {
    const loadContests = async () => {
      const { data } = await supabase.from("contests").select("*").order("created_at", { ascending: false });

      if (data) setContests(data);
    };

    void loadContests();
  }, []);

  const TEST_MODE = portalFundTestMode();

  let totalFund = 0;
  let requiredBuffer = 3000;

  if (TEST_MODE === 0) {
    totalFund = 3000; // surplus = 0
  }

  if (TEST_MODE === 1) {
    totalFund = 3500; // small surplus → weekly only ($500+)
  }

  if (TEST_MODE === 2) {
    totalFund = 13000; // surplus ≥ $10k for monthly (with $3k buffer)
  }

  const surplus = calculateSurplus(totalFund, requiredBuffer);
  const unlocked = getUnlockedTiers(surplus);

  const userTier = getTierFromContribution(
    Number(profile?.season_contribution || 0),
  );

  const contribution = Number(profile?.season_contribution || 0);

  const currentThreshold = TIER_THRESHOLDS[userTier - 1];
  const nextThreshold = TIER_THRESHOLDS[userTier] || null;

  const progressPercent = nextThreshold
    ? Math.min(
        100,
        ((contribution - currentThreshold) / (nextThreshold - currentThreshold)) * 100,
      )
    : 100;

  const amountToNext = nextThreshold ? Math.max(0, nextThreshold - contribution) : 0;

  const unlockedContests = contests.filter((c) => userTier >= c.required_tier);

  const lockedContests = contests.filter((c) => userTier < c.required_tier);

  useEffect(() => {
    // first load — just set baseline
    if (prevTierRef.current === null) {
      prevTierRef.current = userTier;
      return;
    }

    // only trigger on actual increase
    if (userTier > prevTierRef.current) {
      playPortalSound();
      setShowTierUnlock(true);

      setTimeout(() => {
        setShowTierUnlock(false);
      }, 2500);
    }

    prevTierRef.current = userTier;
  }, [userTier]);

  return (
    <div className="relative mx-auto w-full max-w-6xl space-y-8 px-4 py-8 sm:px-6">
      {showWelcome && (
        <div className="mb-6 rounded border border-yellow-500/40 bg-yellow-500/10 p-4">
          <h2 className="mb-2 text-lg font-semibold">Welcome to the Coveted CashCaddies Contests</h2>

          <p className="mb-2 text-sm text-gray-300">
            This portal is where long-term CashCaddies users gain access to exclusive contests with real prizes and cash
            rewards.
          </p>

          <p className="mb-2 text-sm text-gray-300">
            Contests are tiered based on your contributions to the Protection Fund. Smaller bankroll players compete for
            smaller portions, while higher contributors unlock access to larger prize pools generated by the system.
          </p>

          <p className="mb-3 text-sm text-gray-300">
            You can also track prize pools growing day by day as we build toward the Tour Championship — the Top Coveted
            CashCaddies Contest, where the largest added prize money will be available for everyone to compete for.
          </p>

          <button
            type="button"
            onClick={() => {
              localStorage.setItem("cc_portal_welcome_seen", "true");
              setShowWelcome(false);
            }}
            className="rounded bg-yellow-500 px-4 py-1 text-sm text-black"
          >
            Got it
          </button>
        </div>
      )}

      <div className="mb-8 rounded-xl border border-gray-800 bg-black/60 p-5 backdrop-blur-sm">
        <div className="mb-3 text-xs uppercase tracking-widest text-gray-400">How Portal Access Works</div>

        <div className="space-y-2 text-sm text-gray-300">
          <p>Enter contests in the Lobby to contribute to the Protection Fund.</p>

          <p>Your total contribution determines your Tier.</p>

          <p>Higher tiers unlock exclusive Portal contests with larger prize pools.</p>
        </div>

        <button
          type="button"
          onClick={() => router.push("/lobby")}
          className="mt-4 text-sm text-green-400 hover:underline"
        >
          Go to Lobby →
        </button>
      </div>

      <div className="group relative">
        <div className="relative mb-10 overflow-hidden rounded-xl border border-green-500/20 bg-gradient-to-br from-black via-gray-900 to-black p-6 shadow-lg shadow-green-500/10 transition-all duration-300 hover:-translate-y-[2px] hover:shadow-green-500/20">
          <div className="pointer-events-none absolute inset-0 animate-pulse rounded-xl bg-gradient-to-r from-green-500 via-transparent to-green-500 opacity-20 blur-2xl" />
          {/* subtle glow */}
          <div className="pointer-events-none absolute inset-0 rounded-xl bg-gradient-to-r from-green-500 via-transparent to-green-500 opacity-10 blur-lg" />

          <div className="absolute right-4 top-4 text-sm font-semibold text-green-400">Tier {userTier}</div>

          <div className="relative mb-5">
            <div className="text-xs uppercase tracking-widest text-gray-400">Tier Status</div>
          </div>

          <div className="relative flex items-center justify-center gap-4">
            {[1, 2, 3, 4, 5].map((tier) => (
              <div
                key={tier}
                className={`relative flex h-12 w-12 items-center justify-center rounded-full text-sm font-semibold transition-all duration-300 ease-out hover:scale-110 hover:shadow-green-500/40 ${
                  userTier >= tier
                    ? "scale-105 bg-green-500 text-black shadow-lg shadow-green-500/30"
                    : "border border-gray-800 bg-gray-900 text-gray-500"
                }`}
              >
                {tier}

                {userTier === tier && (
                  <div className="absolute inset-0 animate-ping rounded-full opacity-60 ring-2 ring-green-400" />
                )}
              </div>
            ))}
          </div>
        </div>

        <div className="pointer-events-none absolute left-1/2 top-full z-40 mt-3 max-w-[90vw] w-72 whitespace-normal -translate-x-1/2 opacity-0 transition group-hover:opacity-100">
          <div className="relative rounded border border-gray-800 bg-black p-3 text-xs leading-relaxed text-gray-300 shadow-lg">
            <div className="absolute -top-2 left-1/2 h-3 w-3 -translate-x-1/2 rotate-45 border-l border-t border-gray-800 bg-black" />

            <div className="flex items-center gap-2 mb-2">
              <Image
                src={golfBall}
                alt="tier"
                width={28}
                height={28}
                className="pointer-events-none translate-y-[1px]"
              />
              <div className="font-semibold text-white">Tier System</div>
            </div>

            <p className="mb-2">Your tier is based on total contribution to the protection fund.</p>

            <ul className="space-y-1">
              <li>Tier 1 — Entry level access</li>
              <li>Tier 2 — Mid-tier contests unlocked</li>
              <li>Tier 3 — Higher prize pools</li>
              <li>Tier 4 — Premium contests</li>
              <li>Tier 5 — Full access</li>
            </ul>
          </div>
        </div>
      </div>

      <div className="mb-8 rounded-xl border border-gray-800 bg-black/60 p-4 backdrop-blur-sm">
        <div className="mb-2 flex justify-between text-xs text-gray-400">
          <span>
            {nextThreshold
              ? `$${amountToNext.toLocaleString()} to Tier ${userTier + 1}`
              : "Max Tier Reached"}
          </span>

          <span>${contribution.toLocaleString()}</span>
        </div>

        <div className="h-2 w-full overflow-hidden rounded-full bg-gray-900">
          <div
            className="h-full bg-green-500 transition-all"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      <div className="mt-2 text-xs text-gray-500">Earn progress by entering contests in the Lobby.</div>

      <div className="mb-6">
        <h3 className="text-md font-semibold mb-2">Available Contests</h3>

        {unlockedContests.map((c) => (
          <div key={c.id} className="border border-green-500 p-3 rounded mb-2">
            <div>{c.name}</div>
            <div className="text-sm text-gray-400">Tier {c.required_tier}</div>
          </div>
        ))}
      </div>

      <div>
        <h3 className="text-md font-semibold mb-2">Locked Contests</h3>

        {lockedContests.map((c) => (
          <div key={c.id} className="border border-gray-700 p-3 rounded mb-2 opacity-60">
            <div>{c.name}</div>
            <div className="text-sm text-gray-500">Requires Tier {c.required_tier}</div>
          </div>
        ))}
      </div>

      <div className="flex justify-center my-6 relative">
        <div className="pointer-events-none absolute left-1/2 top-1/2 h-16 w-16 -translate-x-1/2 -translate-y-1/2 animate-pulse rounded-full bg-green-500/10 blur-xl" />

        <button
          type="button"
          title="Click here for portal rules"
          onClick={() => {
            playPortalSound();
            setShowRules(true);
          }}
          className="relative z-10 cursor-pointer transition-transform duration-200 ease-out hover:scale-110 active:scale-95 will-change-transform float"
        >
          <Image
            src={golfBall}
            alt="portal rules"
            width={42}
            height={42}
            className="pointer-events-none drop-shadow-md"
          />
        </button>
      </div>

      <div className="space-y-6">
        {/* Fund Display */}
        <div className="rounded-xl border border-white/10 bg-[#0b1220] p-5 text-center">
          <p className="text-xs tracking-widest text-gray-400">CURRENT FUND SURPLUS</p>
          <p className="mt-1 text-2xl font-bold text-white">{formatMoney(surplus)}</p>
        </div>

        {/* WEEKLY */}
        <div>
          <h2 className="mb-2 text-xs tracking-widest text-gray-400">WEEKLY PORTAL</h2>

          <div className="rounded-xl border border-emerald-500/10 bg-[#0b1220] p-5">
            {unlocked.includes("weekly") ? (
              <>
                <p className="text-lg font-semibold text-emerald-400">
                  +{formatMoney(getOverlayAmount(surplus, "weekly"))}
                </p>
                <p className="mt-1 text-sm text-gray-400">Added to prize pool</p>
              </>
            ) : (
              <p className="italic text-gray-500">Locked — awaiting sufficient fund surplus</p>
            )}
          </div>
        </div>

        {/* BI-WEEKLY */}
        <div>
          <h2 className="mb-2 text-xs tracking-widest text-gray-400">BI-WEEKLY PORTAL</h2>

          <div className="rounded-xl border border-blue-500/10 bg-[#0b1220] p-5">
            {unlocked.includes("biweekly") ? (
              <>
                <p className="text-lg font-semibold text-blue-400">
                  +{formatMoney(getOverlayAmount(surplus, "biweekly"))}
                </p>
                <p className="mt-1 text-sm text-gray-400">Added to prize pool</p>
              </>
            ) : (
              <p className="italic text-gray-500">Locked — awaiting sufficient fund surplus</p>
            )}
          </div>
        </div>

        {/* MONTHLY */}
        <div>
          <h2 className="mb-2 text-xs tracking-widest text-gray-400">MONTHLY PORTAL</h2>

          <div className="rounded-xl border border-yellow-500/20 bg-[#0b1220] p-5">
            {unlocked.includes("monthly") ? (
              <>
                <p className="text-lg font-semibold text-yellow-400">
                  +{formatMoney(getOverlayAmount(surplus, "monthly"))}
                </p>
                <p className="mt-1 text-sm text-gray-400">Premium added prize pool</p>
              </>
            ) : (
              <p className="italic text-gray-500">Locked — premium tier requires strong fund surplus</p>
            )}
          </div>
        </div>
      </div>

      {showTierInfo && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80">
          <div className="w-full max-w-lg rounded border border-gray-800 bg-black p-6">
            <h2 className="mb-4 text-xl font-semibold">Tier System</h2>

            <p className="mb-4 text-sm text-gray-300">
              Your tier is based on total contribution to the protection fund.
            </p>

            <ul className="space-y-2 text-sm text-gray-300">
              <li>Tier 1 — Entry level access</li>
              <li>Tier 2 — Mid-tier contests unlocked</li>
              <li>Tier 3 — Higher prize pools</li>
              <li>Tier 4 — Premium contests</li>
              <li>Tier 5 — Full access</li>
            </ul>

            <button
              type="button"
              onClick={() => setShowTierInfo(false)}
              className="mt-6 rounded bg-green-500 px-4 py-2 text-black"
            >
              Close
            </button>
          </div>
        </div>
      )}

      {showRules && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80">
          <div className="w-full max-w-lg rounded border border-gray-800 bg-black p-6">
            <h2 className="mb-4 text-xl font-semibold">Portal Rules</h2>

            <div className="space-y-4 text-sm text-gray-300">
              <div>
                <div className="mb-1 text-xs uppercase text-gray-400">Access</div>
                <p>Portal contests are unlocked based on your total protection fund contribution.</p>
              </div>

              <div>
                <div className="mb-1 text-xs uppercase text-gray-400">Tiers</div>
                <p>Each tier grants access to higher prize contests. Higher tiers = higher upside.</p>
              </div>

              <div>
                <div className="mb-1 text-xs uppercase text-gray-400">Contribution Impact</div>
                <p>A portion of each entry contributes to the protection fund before contests begin.</p>
              </div>

              <div>
                <div className="mb-1 text-xs uppercase text-gray-400">Fund Usage</div>
                <p>
                  The protection fund is used to cover withdrawals, disqualifications, and unexpected outcomes (WD, DQ,
                  DNS).
                </p>
              </div>

              <div>
                <div className="mb-1 text-xs uppercase text-gray-400">Tier Maintenance</div>
                <p>
                  Your tier is based on total contribution. Maintain or increase contribution to retain access.
                </p>
              </div>
            </div>

            <button
              type="button"
              onClick={() => setShowRules(false)}
              className="mt-6 rounded bg-green-500 px-4 py-2 text-black"
            >
              Close
            </button>
          </div>
        </div>
      )}

      {showTierUnlock && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70">
          <div className="relative text-center">
            <div className="mb-2 animate-pulse text-2xl font-semibold text-green-400">Tier Unlocked</div>

            <div className="mb-4 text-4xl font-bold text-white">Tier {userTier}</div>

            <div className="flex justify-center">
              <Image src={golfBall} alt="unlock" width={80} height={80} className="animate-bounce" />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
