"use client";

import { useEffect, useState } from "react";
import { calculateSurplus, getOverlayAmount, getUnlockedTiers } from "@/lib/portal-logic";
import { getTierFromContribution } from "@/lib/tiers";
import { supabase } from "@/lib/supabase/client";

function formatMoney(value: number | string | null | undefined): string {
  const n = Number(value ?? 0);
  if (!Number.isFinite(n)) return "$0";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);
}

function portalFundTestMode(): 0 | 1 | 2 {
  // Change return value to test different states — remove when Supabase supplies fund data
  return 2;
}

export default function PortalPage() {
  const [showWelcome, setShowWelcome] = useState(false);
  const [profile, setProfile] = useState<any>(null);
  const [contests, setContests] = useState<any[]>([]);

  useEffect(() => {
    const loadProfile = async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession();

      if (!session?.user?.id) return;

      const { data } = await supabase.from("profiles").select("*").eq("id", session.user.id).single();

      if (data) {
        setProfile(data);
        if (!data.has_seen_portal_welcome) {
          setShowWelcome(true);
        }
      }
    };

    void loadProfile();
  }, []);

  useEffect(() => {
    const loadContests = async () => {
      const { data } = await supabase.from("contests").select("*").order("created_at", { ascending: false });

      if (data) setContests(data);
    };

    void loadContests();
  }, []);

  const handleCloseWelcome = async () => {
    const {
      data: { session },
    } = await supabase.auth.getSession();

    if (!session?.user?.id) return;

    await supabase.from("profiles").update({ has_seen_portal_welcome: true }).eq("id", session.user.id);

    setShowWelcome(false);
  };

  const TEST_MODE = portalFundTestMode();

  let totalFund = 0;
  let requiredBuffer = 3000;

  if (TEST_MODE === 0) {
    totalFund = 3000; // surplus = 0
  }

  if (TEST_MODE === 1) {
    totalFund = 3500; // small surplus → weekly only ($500+)
  }

  if (TEST_MODE === 2) {
    totalFund = 13000; // surplus ≥ $10k for monthly (with $3k buffer)
  }

  const surplus = calculateSurplus(totalFund, requiredBuffer);
  const unlocked = getUnlockedTiers(surplus);

  const userTier = getTierFromContribution(
    Number(profile?.season_contribution || 0),
  );

  const unlockedContests = contests.filter((c) => userTier >= c.required_tier);

  const lockedContests = contests.filter((c) => userTier < c.required_tier);

  return (
    <div className="mx-auto w-full max-w-6xl space-y-8 px-4 py-8 sm:px-6">
      {showWelcome && (
        <div className="mb-6 rounded border border-yellow-500/40 bg-yellow-500/10 p-4">
          <h2 className="mb-2 text-lg font-semibold">Welcome to the Coveted CashCaddies Contests</h2>

          <p className="mb-2 text-sm text-gray-300">
            This portal is where long-term CashCaddies users gain access to exclusive contests with real prizes and cash
            rewards.
          </p>

          <p className="mb-2 text-sm text-gray-300">
            Contests are tiered based on your contributions to the Protection Fund. Smaller bankroll players compete for
            smaller portions, while higher contributors unlock access to larger prize pools generated by the system.
          </p>

          <p className="mb-3 text-sm text-gray-300">
            You can also track prize pools growing day by day as we build toward the Tour Championship — the Top Coveted
            CashCaddies Contest, where the largest added prize money will be available for everyone to compete for.
          </p>

          <button
            type="button"
            onClick={handleCloseWelcome}
            className="rounded bg-yellow-500 px-4 py-1 text-sm text-black"
          >
            Got it
          </button>
        </div>
      )}

      <header className="rounded-2xl border border-violet-500/30 bg-gradient-to-br from-[#140b2a] via-[#141a33] to-[#0d1524] p-6">
        <p className="text-xs font-semibold uppercase tracking-[0.24em] text-violet-200/90">Special Access</p>
        <h1 className="mt-2 text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Portal Contests</h1>
        <p className="mt-2 text-sm text-violet-100/80">
          Premium portal contest drops, organized by cadence.
        </p>
      </header>

      <div className="mb-6 flex justify-center">
        <div className="group relative cursor-pointer">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-green-600 text-lg font-bold text-white">
            ?
          </div>
          <div className="absolute bottom-full left-1/2 z-10 mb-2 hidden -translate-x-1/2 rounded bg-black px-2 py-1 text-xs whitespace-nowrap text-white group-hover:block">
            Portal Access
          </div>
        </div>
      </div>

      <div className="space-y-6">
        {/* Fund Display */}
        <div className="rounded-xl border border-white/10 bg-[#0b1220] p-5 text-center">
          <p className="text-xs tracking-widest text-gray-400">CURRENT FUND SURPLUS</p>
          <p className="mt-1 text-2xl font-bold text-white">{formatMoney(surplus)}</p>
        </div>

        {/* WEEKLY */}
        <div>
          <h2 className="mb-2 text-xs tracking-widest text-gray-400">WEEKLY PORTAL</h2>

          <div className="rounded-xl border border-emerald-500/10 bg-[#0b1220] p-5">
            {unlocked.includes("weekly") ? (
              <>
                <p className="text-lg font-semibold text-emerald-400">
                  +{formatMoney(getOverlayAmount(surplus, "weekly"))}
                </p>
                <p className="mt-1 text-sm text-gray-400">Added to prize pool</p>
              </>
            ) : (
              <p className="italic text-gray-500">Locked — awaiting sufficient fund surplus</p>
            )}
          </div>
        </div>

        {/* BI-WEEKLY */}
        <div>
          <h2 className="mb-2 text-xs tracking-widest text-gray-400">BI-WEEKLY PORTAL</h2>

          <div className="rounded-xl border border-blue-500/10 bg-[#0b1220] p-5">
            {unlocked.includes("biweekly") ? (
              <>
                <p className="text-lg font-semibold text-blue-400">
                  +{formatMoney(getOverlayAmount(surplus, "biweekly"))}
                </p>
                <p className="mt-1 text-sm text-gray-400">Added to prize pool</p>
              </>
            ) : (
              <p className="italic text-gray-500">Locked — awaiting sufficient fund surplus</p>
            )}
          </div>
        </div>

        {/* MONTHLY */}
        <div>
          <h2 className="mb-2 text-xs tracking-widest text-gray-400">MONTHLY PORTAL</h2>

          <div className="rounded-xl border border-yellow-500/20 bg-[#0b1220] p-5">
            {unlocked.includes("monthly") ? (
              <>
                <p className="text-lg font-semibold text-yellow-400">
                  +{formatMoney(getOverlayAmount(surplus, "monthly"))}
                </p>
                <p className="mt-1 text-sm text-gray-400">Premium added prize pool</p>
              </>
            ) : (
              <p className="italic text-gray-500">Locked — premium tier requires strong fund surplus</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
